### ISSUE TITLE
Not working on Firefox 59.0.2

### ISSUE THREAD

**Issue by Nouniz** [OneSignal/OneSignal-WordPress-Plugin#124]
**Description:**
Notifications don't work on Firefox 59.0.2

**Steps to Reproduce Issue:**

  1.  Go to http://www.medyaturk.info/
  2. Wait for notification

**Anything else:**

It works on Safari and Chrome but not on Firefox 59.0.2

I followed this instructions : https://documentation.onesignal.com/docs/troubleshooting-web-push AND this https://documentation.onesignal.com/docs/troubleshooting-web-push#section-debugging-using-browser-developer-tools

With Firefox console, on step 2 I got undefined and when I test if I am subscriber I got `OneSignal.isOptedOut is not a function`

**Comment by LaconicTranslator** [comment]
I confirm that the website in question behaves differently on Safari and Firefox. 
On Safari it immediately suggests to subscribe, while on Firefox it does not. 
Remember, for Firefox there are tree options when browser ask for user permission: enable, disable and "not now". 
The latter tends to mess up OneSignal's logic. I'll try to reproduce and report the issue properly some day.

**Comment by fatsjohonimahnn** [comment]
Closing due to inactivity, please contact OneSignal support with your App ID and a link to this issue if you need further assistance.
